sider/meowcop

config/rubocop.yml
In RuboCop's default, TargetRubyVersion is 2.0.
But we almost use the higher version.
If TargetRubyVersion is older than used ruby version, RuboCop says
`unexpected token ...` It's a false positive detection. So, I've specify
the newest ruby version.
Problem
-------
In the setting, RuboCop may detects false negative when use older ruby
version than TargetRubyVersion. But I think it is not important.
=> Specify TargetRubyVersion

config/rubocop.yml
I've checked https://github.com/bbatsov/rubocop/commit/49c32a803e1610df7b6e196e5e9b62d56e6ce7c3
=> RuboCop 0.47.0

config/rubocop.yml
By the change, user can receive more information about warnings.
In many cops, there is not much information contained in the message.
But more details exist in the style guide. 
And cop name is useful for google-ability.
=> Display cop name and style guide URL by default

config/rubocop.yml, meowcop.gemspec
RuboCop 0.56.0 made `Style/MethodMissing` cop split into two cops. I'd like to follow the change.
See: https://github.com/bbatsov/rubocop/pull/5811
=> Split Style/MethodMissing to follow RuboCop 0.56.0

config/rubocop.yml
- `Style/ExtendSelf` is removed in v0.52.1 https://github.com/rubocop-hq/rubocop/pull/5233
- `Style/MethodRespondToMissing` is typo. It is `Style/MissingRespondToMissing` https://github.com/sideci/meowcop/pull/26
```
$ rubocop
Warning: unrecognized cop Style/ExtendSelf found in /home/wata727/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/meowcop-1.16.0/config/rubocop.yml
Warning: unrecognized cop Style/MethodRespondToMissing found in /home/wata727/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/meowcop-1.16.0/config/rubocop.yml
Warning: unrecognized cop Style/ExtendSelf found in .rubocop.yml
Warning: unrecognized cop Style/MethodRespondToMissing found in .rubocop.yml
Inspecting 0 files            
0 files inspected, no offenses detected
```
```
$ rubocop
Inspecting 0 files            
0 …
```
=> Fix unrecognized cops warnings

config/rubocop.yml
https://github.com/rubocop-hq/rubocop/blob/v0.57.2/manual/cops_style.md#styleunpackfirst
**Enabled**
This cop suggests to use `unpack1` instread of `unpack` when pick up first value. `unpack1` is superior to `unpack` in terms of performance. I judged that there was little effect on existing code.
https://github.com/rubocop-hq/rubocop/blob/v0.57.2/manual/cops_rails.md#railshttpstatus
**Disabled**
This is focus on style.
**Enabled**
https://github.com/rubocop-hq/rubocop/blob/v0.57.2/manual/cops_performance.md#performanceunneededsort
https://github.com/rubocop-hq/rubocop/blob/v0.57.2/manual/cops_lint.md#lintsafenavigationconsistency
**Enabled**
https://github.com/rubocop-hq/rubocop/blob/v0.57.2/manual/cops_performance.md#performanceinefficienthashsearch
**Enabled** …
=> Follow up of new cops (v0.54.0 ~ v0.56.0)

README.md, examples/.rubocop.yml
As of RuboCop v0.58.0, it supports 2.2 or later. See https://github.com/rubocop-hq/rubocop/pull/5990
=> Change default ruby version to 2.2

config/rubocop.yml
See also https://github.com/rubocop-hq/rubocop/releases/tag/v0.59.0
There are no new cops in v0.59.0, but enabled `Layout/EmptyLineAfterGuardClause` cop by default from this version. Since this cop focuses on the style, I judged that it should be disabled in MeowCop.
=> Follow up of new cops (v0.59.0)

config/rubocop.yml, meowcop.gemspec
Fixes #39 
https://github.com/rubocop-hq/rubocop/releases/tag/v0.67.0
- Add new multiline element line break cops.
- https://github.com/rubocop-hq/rubocop/pull/6824
- `Layout/MultilineArrayLineBreaks`, `Layout/MultilineHashKeyLineBreaks` and `Layout/MultilineMethodArgumentLineBreaks` forces on style issues, but these are disabled by default.
- Add new cop Rails/ActiveRecordOverride that checks for overriding Active Record methods instead of using callbacks.
- https://github.com/rubocop-hq/rubocop/pull/6853
- IMO, this is a style issue.
- Add new cop Rails/RedundantAllowNil that checks for cases when allow_blank makes allow_nil unnecessary in model validations.
- https://github.com/rubocop-hq/rubocop/pull/6848
- This Cop can warn of unintended validation behavior. I decided that it should …
=> Follow up of new cops (v0.67)

config/rubocop.yml
If it ran with Rubocop v0.68, it causes error with following message.
```
$ bundle exec rubocop
Error: The `Layout/FirstParameterIndentation` cop has been renamed to `Layout/IndentFirstArgument`.
(obsolete configuration found in vendor/bundle/ruby/2.6.0/gems/meowcop-1.18.0/config/rubocop.yml, please update it)
The `Layout/IndentArray` cop has been renamed to `Layout/IndentFirstArrayElement`.
(obsolete configuration found in vendor/bundle/ruby/2.6.0/gems/meowcop-1.18.0/config/rubocop.yml, please update it)
The `Layout/IndentHash` cop has been renamed to `Layout/IndentFirstHashElement`.
(obsolete configuration found in vendor/bundle/ruby/2.6.0/gems/meowcop-1.18.0/config/rubocop.yml, please update it)
```
This patch will fix the errors.
=> Rename some cops to follow up of Rubocop v0.68

config/rubocop.yml, meowcop.gemspec
See also https://github.com/sider/meowcop/pull/41
- `Layout/AlignArguments`
- `Layout/HeredocArgumentClosingParenthesis`
- `Layout/IndentFirstParameter`
- These cops also focused on styles(layouts).
- `Performance/RedundantBlockCall`
- Performance cops are extracted as `rubocop-performance`. See https://github.com/rubocop-hq/rubocop/issues/5977
- `Lint/HeredocMethodCallPosition`
- Certainly, it focuses on styles, but it also suggests avoiding possible errors. This is a difficult problem, but I decided to enable it here. See https://github.com/rubocop-hq/rubocop/pull/6989
=> RuboCop v0.68

README.md, config/rubocop.yml, examples/.rubocop.yml, meowcop.gemspec
Fixes #49 
See https://github.com/rubocop-hq/rubocop/releases/tag/v0.72.0
- `Gemspec/RubyVersionGlobalsUsage`
- :+1: It focused on linting.
- `Style/FloatDivision`
- This is a style issue. Disabled.
- Remove Rails cops
- We also remove Rails cops configuration from the gem.
=> Follow up of RuboCop v0.72

.gitignore
> `bundle install --deployment` installs gems to the `vendor/bundle` directory in the application.
https://bundler.io/man/bundle-install.1.html#DEPLOYMENT-MODE
=> Ignore `vendor/bundle` directory on Git

config/rubocop.yml, meowcop.gemspec
See https://github.com/rubocop-hq/rubocop/releases/tag/v0.73.0
- `Style/MultilineWhenThen`
- Style. Disabled
=> Follow up of RuboCop v0.73

LICENSE, meowcop.gemspec
- Add missing OSS license: MIT
- Update gemspec (authors, email, metadata, etc.)
=> Add license and update gemspec

Rakefile, config/rubocop.yml
Reverts sider/meowcop#62
`Style/StringHashKeys: { Enabled: true }` cannot override `Style: { Enabled: false }` with [RuboCop 0.75.0](https://github.com/rubocop-hq/rubocop/releases/tag/v0.75.0).
https://github.com/sider/meowcop/blob/f8785421ce21f03526bc90d8f33e36b1a58d7833/config/rubocop.yml#L261-L262
=> Revert "Disable all Style Cops"

test/smoke/Dockerfile
Run `rake install` instead of `gem install meowcop`.
Because we should test the local code instead of the published code.
=> Test local code on smoke test

meowcop.gemspec
- https://github.com/rubocop-hq/rubocop/releases/tag/v0.75.0
- https://github.com/rubocop-hq/rubocop/releases/tag/v0.74.0
No new cops.
=> Follow up of RuboCop v0.74 and v0.75

CHANGELOG.md, meowcop.gemspec
Following RuboCop master:
https://github.com/rubocop-hq/rubocop/blob/f50749723726c31c3ac52402632a2907505feea1/rubocop.gemspec#L11
=> Set `>= 2.3.0` to `required_ruby_version`

Rakefile, config/rubocop.yml, meowcop.gemspec
Usage:
```
$ rake config:generate config:verify
```
This PR is another approach of #71.
=> Disable all Style Cops automatically

CHANGELOG.md, config/rubocop.yml, meowcop.gemspec
- https://github.com/rubocop-hq/rubocop/releases/tag/v0.76.0
- https://github.com/rubocop-hq/rubocop/blob/v0.76.0/CHANGELOG.md
- (Breaking) Rename `Unneeded*` cops to `Redundant*`.
=> Follow up of RuboCop v0.76 (including breaking changes)

CHANGELOG.md, LICENSE, meowcop.gemspec
[Sleeek Corporation](https://www.sleeek.io/) owns Sider now.
See our [blog post](https://blog.sideci.com/siders-operating-company-will-change-to-sleeek-co-ltd-on-october-31-2019-a86c37fc7a4f) for details.
=> Change the gem's author

CHANGELOG.md, config/rubocop.yml, meowcop.gemspec
- https://github.com/rubocop-hq/rubocop/releases/tag/v0.77.0
- https://github.com/rubocop-hq/rubocop/blob/v0.77.0/CHANGELOG.md
This includes breaking changes since RuboCop v0.77.0.
The changes is renaming some cops for consistency.
See rubocop-hq/rubocop#7077 for details.
=> Follow up RuboCop v0.77 (including breaking changes)

.github/workflows/test.yml, CHANGELOG.md, config/rubocop.yml, meowcop.gemspec, test/smoke/Dockerfile
- https://github.com/rubocop-hq/rubocop/releases/tag/v0.78.0
- https://github.com/rubocop-hq/rubocop/pull/7542 (breaking)
Here is the breaking error message:
> Metrics/LineLength has the wrong namespace - should be Layout
=> Follow up RuboCop v0.78 (breaking)

.github/workflows/test.yml
https://github.blog/changelog/2019-10-17-github-actions-removing-python-3-4-and-ruby-2-3-from-the-virtual-environments/
=> Ruby 2.3 on GitHub Actions

.github/workflows/release.yml, .github/workflows/test.yml
See https://github.com/actions/checkout/releases/tag/v2.0.0
=> Bump actions/checkout from v1 to v2

.github/workflows/test.yml
This migrates from the official actions/setup-ruby to eregon/use-ruby-action.
Because the later supports also Ruby 2.3 in addition to Ruby 2.7.
- https://github.com/actions/setup-ruby
- https://github.com/eregon/use-ruby-action
Close #86
=> Test Ruby 2.7 on CI

CHANGELOG.md, config/rubocop.yml, meowcop.gemspec
Release note: <https://github.com/rubocop-hq/rubocop/releases/tag/v0.80.0>
- (breaking) Remove `Style/BracesAroundHashParameters` cop. See <https://github.com/rubocop-hq/rubocop/issues/7641>.
- Disable some new `Style` cops.
=> Follow up RuboCop v0.80 (breaking)

.github/workflows/test.yml
- Simplify `on:` setting.
- Use [ruby/setup-ruby](https://github.com/ruby/setup-ruby) instead of [eregon/use-ruby-action](https://github.com/eregon/use-ruby-action)
- Use `bundle config set` instead of `bundle install --path` option.
See <https://github.com/rubygems/bundler/blob/master/UPGRADING.md#cli-deprecations>
=> Update CI configurations

README.md, meowcop.gemspec
Sider, Inc. does not exist, so this renames it from the company name to the service name.
=> Fix company name

.github/workflows/release.yml, .github/workflows/test.yml, CHANGELOG.md, config/rubocop.yml, meowcop.gemspec
See <https://github.com/rubocop-hq/rubocop/releases/tag/v0.82.0>
RuboCop 0.82 has dropped the support for Ruby 2.3. It requires Ruby 2.4+.
=> Follow up RuboCop v0.82 (breaking)

CHANGELOG.md, Rakefile, config/rubocop.yml, meowcop.gemspec, test/smoke/Dockerfile, test/smoke/expectation-output.txt, test/smoke/expectation-output2.txt
- https://github.com/rubocop-hq/rubocop/releases/tag/v0.86.0
- https://github.com/rubocop-hq/rubocop/releases/tag/v0.85.0
- https://github.com/rubocop-hq/rubocop/releases/tag/v0.84.0
- https://github.com/rubocop-hq/rubocop/releases/tag/v0.83.0
=> Follow up RuboCop v0.86

CHANGELOG.md, lib/meowcop.rb, lib/meowcop/cli.rb, lib/meowcop/version.rb, meowcop.gemspec, test/meowcop/cli_test.rb
- Add a `version` sub-command to show this gem version.
- Exit with `1` when the sub-command is invalid.
- Add a `MeowCop` alias to the `Meowcop` module.
=> Empower CLI

test/meowcop/cli_test.rb
```
test_version#CLITest (0.10s)
In stdout.
--- expected
+++ actual
@@ -1,2 +1,2 @@
-"2.9.0
+"2.10.0
"
/home/runner/work/meowcop/meowcop/test/meowcop/cli_test.rb:56:in `test_version'
```
=> Fix `CLITest#test_version` due to version-up

.rubocop.yml, CHANGELOG.md, config/rubocop.yml, meowcop.gemspec
https://github.com/rubocop-hq/rubocop/releases/tag/v0.87.0
Some style cops since v0.87 are disabled.
=> Follow up RuboCop v0.87

CHANGELOG.md, README.md, examples/.rubocop.yml
This change aims to remove the `AllCops.TargetRubyVersion` setting
from a `.rubocop.yml` file generated by the `meowcop init` command.
Reasons:
- We need to update `TargetRubyVersion` in the future if a new version of Ruby will be released.
- Uses need to remove `TargetRubyVersion` manually if they uses their `.ruby-version` file.
For the reasons above, I don't think `TargetRubyVersion` is useful.
See also <https://docs.rubocop.org/rubocop/configuration.html#setting-the-target-ruby-version>
=> Remove `AllCops.TargetRubyVersion`

.github/workflows/release.yml
For the changelog URL, this uses a tag instead of a commit SHA.
=> Improve release workflow on Actions

CHANGELOG.md, config/rubocop.yml, goodcheck.yml, meowcop.gemspec
https://github.com/rubocop-hq/rubocop/releases/tag/v0.93.0
- Disabled the new `Style/ClassEqualityComparison` cop.
=> Follow up RuboCop v0.93

CHANGELOG.md, config/rubocop.yml
The `Max` default value of `Metrics/BlockNesting` is **3** but I think it's a bit too strict.
https://docs.rubocop.org/rubocop/1.4/cops_metrics.html#metricsblocknesting
=> Loosen the max value of `Metrics/BlockNesting`

.github/workflows/test.yml, CHANGELOG.md, meowcop.gemspec
The support of Ruby 2.4 has ended, and RuboCop also has dropped it.
See also:
- https://www.ruby-lang.org/en/news/2020/04/05/support-of-ruby-2-4-has-ended/
- https://github.com/rubocop/rubocop/releases/tag/v1.13.0
=> Drop support for Ruby 2.4

.github/workflows/release.yml
The GitHub CLI (the `gh` command) is pre-installed, so the 3rd-party action is no longer needed.
=> Replace `softprops/action-gh-release` with GitHub CLI
