config/rubocop.yml

Enable Metrics/* cops

---

config/rubocop.yml

Update for RuboCop 0.44.1

---

config/rubocop.yml

Support RuboCop 0.45.0

---

examples/.rubocop.yml
exe/meowcop
lib/meowcop.rb
lib/meowcop/cli.rb

Add MeowCop CLI to initialise configuration file

---

config/rubocop.yml
examples/.rubocop.yml

#20 
https://github.com/bbatsov/rubocop/releases/tag/v0.48.0

[Close #20] Support RuboCop 0.48.0

---

config/rubocop.yml

Rubocop 0.49

---

config/rubocop.yml

latest rubocop changes some cops namespace.

follow rubocop's namespace change

---

config/rubocop.yml
meowcop.gemspec

See also: https://github.com/sideci/meowcop/pull/29

Follow up of new cops (v0.57.0)

---

README.md
config/rubocop.yml
examples/.rubocop.yml
meowcop.gemspec

Follow up of RuboCop v0.69.0

---

CHANGELOG.md

Add changelog entry for v2

---

CHANGELOG.md
README.md
meowcop.gemspec

Old: Actcat, SideCI
New: Sider

Fix old company name

---

CHANGELOG.md
lib/meowcop/version.rb

https://github.com/sider/meowcop/compare/v2.1.0...8e4f52a2565b4f55ed64d2158ff1fc8213ac13e3

Release 2.2.0

---

Rakefile
test/smoke/Dockerfile
test/smoke/test.rb
test/smoke_test.rb

- Remove unused test file.
- More readable Dockerfile.

Improve smoke test

---

meowcop.gemspec

Archive the following files only:
- LICENSE
- README
- Files needed for execution

Lighten the archived gem size

---

test/smoke/Dockerfile
test/smoke/test.rb

https://github.com/sider/meowcop/blob/f8785421ce21f03526bc90d8f33e36b1a58d7833/config/rubocop.yml#L261-L262
Related to #62

Add smoke test case for `Style/StringHashKeys` cop

---

Rakefile
test/smoke/Dockerfile
test/smoke/expectation-output.txt

By comparing the entire output of `rubocop` command.

More accurate smoke test

---

Rakefile
test/smoke/Dockerfile
test/smoke/expectation-output.txt
test/smoke/test.rb

Also, this outputs a result of failed smoke tests.

Add smoke test case

---

Rakefile
config/rubocop.yml

- Remove duplicate `Style/StringHashKeys` setting.
- A bit safer generation.

[Refactor] Improve config file generation

---

.github/workflows/release.yml

See https://github.com/softprops/action-gh-release

Auto-release via GitHub Actions

---

.gitignore

Ignore `.ruby-version`

---

CHANGELOG.md
Rakefile
config/rubocop.yml
meowcop.gemspec
test/smoke/Dockerfile
test/smoke/expectation-output1.txt

https://github.com/rubocop-hq/rubocop/releases/tag/v0.88.0

Follow up RuboCop v0.88

---

.github/workflows/test.yml

To check whether MeowCop works with the latest RuboCop.
Close #101

Run test on Actions daily

---

CHANGELOG.md
config/rubocop.yml
meowcop.gemspec
test/smoke/expectation-output1.txt

https://github.com/rubocop-hq/rubocop/releases/tag/v0.89.0

Follow up RuboCop v0.89

---

CHANGELOG.md
config/rubocop.yml
meowcop.gemspec
test/smoke/Dockerfile
test/smoke/expectation-output1.txt
test/smoke/expectation-output2.txt

See <https://github.com/rubocop-hq/rubocop/releases/tag/v0.90.0>

Follow up RuboCop v0.90

---

.github/workflows/test-edge.yml
.github/workflows/test.yml

- Use `bundler-cache: true`
- Add `head` to matrix
See <https://github.com/ruby/setup-ruby#usage>

Refactor CI configurations

---

CHANGELOG.md
lib/meowcop/version.rb
sider.yml

https://github.com/sider/meowcop/compare/v2.15.1...HEAD

Release 3.0.0

---

CHANGELOG.md
lib/meowcop/version.rb

https://github.com/sider/meowcop/compare/v3.0.0...c8be46554936dec1bb7f23b34839ce6a9ace114b

Release 3.0.1

---

test/smoke/expectation-output1.txt

https://github.com/sider/meowcop/actions/runs/411842698

Fix smoke test with the latest RuboCop
